USE [master]
GO

/****** Object:  Database [Contract]    Script Date: 08.06.2016 15:09:15 ******/
CREATE DATABASE [Contract]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Contract', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEX\MSSQL\DATA\Contract.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Contract_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEX\MSSQL\DATA\Contract_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Contract] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Contract].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Contract] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Contract] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Contract] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Contract] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Contract] SET ARITHABORT OFF 
GO

ALTER DATABASE [Contract] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Contract] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Contract] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Contract] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Contract] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Contract] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Contract] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Contract] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Contract] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Contract] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Contract] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Contract] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Contract] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Contract] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Contract] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Contract] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Contract] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Contract] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Contract] SET  MULTI_USER 
GO

ALTER DATABASE [Contract] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Contract] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Contract] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Contract] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Contract] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Contract] SET  READ_WRITE 
GO


